export const GET_CART = 'CART/GET_CART'

export const GET_CART_START = 'CART/GET_CART_START'

export const GET_CART_END = 'CART/GET_CART_END'

export const GET_CART_SUCCESS = 'CART/GET_CART_SUCCESS'

export const ADD_TO_CART = 'CART/ADD_TO_CART'

export const UPDATE_CART = 'CART/UPDATE_CART'

export const REMOVE_PRODUCT_FROM_CART = 'CART/REMOVE_PRODUCT_FROM_CART'

export const CLEAR_CART = 'CART/CLEAR_CART'

export const ADD_TO_CART_START = 'CART/ADD_TO_CART_START'

export const ADD_TO_CART_SUCCESS = 'CART/ADD_TO_CART_SUCCESS'










