import { Product } from "../models/product";

export default products = [
    {
       "description":"addwad",
       "id":"-MtF5fj1407QSE7TOEX7",
       "imageUrl":"fdsfs",
       "ownerId":"mHeIebO1L6WMq40Y8zbKJekxgw82",
       "price":31231,
       "title":"dwdadaf"
    },
    {
       "description":"ddsdddddddddddddddddddd",
       "id":"-Mv3n4IADIM7cDjEjWQE",
       "imageUrl":"https://m.media-amazon.com/images/I/71s9403-+NS._AC_SY450_.jpg",
       "ownerId":"439bVLJGb8SeoJ5pqQPg31KMRlq1",
       "price":150000,
       "title":"test"
    },
    {
       "description":"concak",
       "id":"-MylBjBXfJCDRYfOAj2U",
       "imageUrl":"https://monanngon.vn/wp-content/uploads/2021/01/banh-mi-viet-nam_13.jpg",
       "ownerId":"uOeU7u736gP6KP4P1EkqF76QZl92",
       "price":22,
       "title":"aaaaaa"
    },
    {
       "description":"lalalala",
       "id":"-MyoWgrfrlolvxWjGqZf",
       "imageUrl":"https://monanngon.vn/wp-content/uploads/2021/01/banh-mi-viet-nam_13.jpg",
       "ownerId":"YS16B1fgnLNthgIPH8X9AtdplI33",
       "price":222,
       "title":"aaa"
    },
    {
       "description":"la 1 chon sach noi ve j do mnnannnn in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions",
       "id":"-MypZeKe0pwudjlpNQBT",
       "imageUrl":"https://cf.shopee.vn/file/679a52afaaaf15ad1e145f9290eb90f5",
       "ownerId":"GFBxTCm2sHYaql7vBBogHt4dtts2",
       "price":22,
       "title":"sach tieng viet"
    },
    {
       "description":"23123",
       "id":"-N-nQ64YV8n7ildX8Kvl",
       "imageUrl":"sss",
       "ownerId":"9YgKyqGpyTY1q7rVmqY3q0o50Ux2",
       "price":1231,
       "title":"nam"
    },
    {
       "description":"fdfdf",
       "id":"-N186bc5YBkqH7HpHc6x",
       "imageUrl":"https://kenh14cdn.com/thumb_w/660/2020/7/17/brvn-15950048783381206275371.jpg",
       "ownerId":"6rSxQkzmsNPpASkPJsYy220SD2w1",
       "price":45,
       "title":"fdfsudad"
    },
    {
       "description":"gfgfggfg",
       "id":"-N18BJfnhKHAuMPesnXg",
       "imageUrl":"https://kenh14cdn.com/thumb_w/660/2020/7/17/brvn-15950048783381206275371.jpg",
       "ownerId":"6rSxQkzmsNPpASkPJsYy220SD2w1",
       "price":54,
       "title":"fdfdf"
    }
 ]