export const LOGIN = 'AUTH/LOGIN'

export const LOGIN_LOADING = 'AUTH/LOGIN_LOADING'

export const LOGIN_SUCESS = 'AUTH/LOGIN_SUCESS'

export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL'

export const SIGNUP = 'AUTH/SIGNUP'

export const SIGNUP_LOADING = 'AUTH/SIGNUP_LOADING'

export const SIGNUP_SUCESS = 'AUTH/SIGNUP_SUCESS'

export const SIGNUP_FAIL = 'AUTH/SIGNUP_FAIL'

export const TRY_LOGIN_LOCAL = 'AUTH/TRY_LOGIN_LOCAL'

export const TRY_LOGIN_LOCAL_START = 'AUTH/TRY_LOGIN_LOCAL_START'

export const TRY_LOGIN_LOCAL_END = 'AUTH/TRY_LOGIN_LOCAL_END'

export const LOGOUT = 'AUTH/LOGOUT'

export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS'

export const GET_USER = 'AUTH/GET_USER'

export const UPDATE_PHONE = 'AUTH/UPDATE_PHONE'

export const UPDATE_NAME = 'AUTH/UPDATE_NAME'

export const UPDATE_ADDRESS = 'AUTH/UPDATE_ADDRESS'

export const UPDATE_GENDER = 'AUTH/UPDATE_GENDER'

export const UPDATE_BIRTHDAY = 'AUTH/UPDATE_BIRTHDAY'

export const UPDATE_URLAVT = 'AUTH/UPDATE_URLAVT'






