export const GET_ORDERS = 'ORDER/GET_ORDERS'

export const GET_ORDERS_START = 'ORDER/GET_ORDERS_START'

export const GET_ORDERS_SUCCESS = 'ORDER/GET_ORDERS_SUCCESS'

export const GET_ORDERS_ERROR = 'ORDER/GET_ORDERS_ERROR'

export const CREATE_ORDER = 'ORDER/CREATE_ORDER'

export const CREATE_ORDER_SUCCESS = 'ORDER/CREATE_ORDER_SUCCESS'

export const CREATE_ORDER_START = 'ORDER/CREATE_ORDER_START'

export const GET_ORDERS_NO_SHOW_LOADING = 'ORDER/GET_ORDERS_NO_SHOW_LOADING'
















