export const GET_FAVORITE_PRODUCTS = 'favorite/GET_FAVORITE_PRODUCTS'

export const GET_FAVORITE_PRODUCTS_FAIL = 'favorite/GET_FAVORITE_PRODUCTS_FAIL'

export const GET_FAVORITE_PRODUCTS_SUCCESS = 'favorite/GET_FAVORITE_PRODUCTS_SUCCESS'

export const GET_FAVORITE_PRODUCTS_START = 'favorite/GET_FAVORITE_PRODUCTS_START'

export const REMOVE_FAVORITE_PRODUCT = 'favorite/REMOVE_FAVORITE_PRODUCT'

export const ADD_FAVORITE_PRODUCT = 'favorite/ADD_FAVORITE_PRODUCT'


















